project_name: stroke
experiment_name: ResNet-50-WBCE-lr1e-4-bsize-16-pretrained-0-dataaug-2-TL-0
seed: 42
device: cuda
resume: false
pretrained: false
checkpoint:
  on_epoch: 2
log:
  on_epoch: 1
stdout:
  verbose: true
  on_batch: 0
  on_epoch: 1
root: D:\Gorkem Can Ates\PycharmProjects\stroke-segmentation-challenge
neptune:
  workspace: machining
  project: stroke
  tags:
  - Stroke
  - ResNet-50-WBCE-lr1e-4-bsize-16-pretrained-0-dataaug-2-TL-0
  source_files:
  - ./stroke-experiment.py
lr: 0.0001
weight_decay: 0.0
epoch: 100
batch_size: 16
validation_batch_size: 16
